job.type: train
dataset:
  name: toy

train:
  type: negative_sampling
  batch_size: 100
  loss: se
  loss_arg: 4.0
  max_epochs: 200
  optimizer.default:
    type: Adagrad
    args:
      lr: 0.1

valid:
  early_stopping.patience: 5
  every: 10
  metric: mean_reciprocal_rank_filtered_with_test

eval:
  batch_size: 512

negative_sampling:
  num_samples.s: 3  # default: p=0; o=s
  sampling_type: uniform

model: scoring_ensemble

scoring_ensemble:
  base_models: [complex, distmult, rotate, conve]
  evaluator: avg
