job.type: train
dataset:
  name: fb15k-237
  files:
    train:
      source: train_ensemble
    valid:
      source: valid_ensemble

train:
  type: negative_sampling
  batch_size: 128
  loss: kl
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 400
  optimizer.default:
    type: Adam
    args:
      lr: 0.1

eval:
  batch_size: 128
  metrics_per:
    relation_type: true
  trace_level: example

valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

negative_sampling:
  num_samples.s: 3

model: embedding_ensemble

embedding_ensemble:
  base_models: [complex, literale_distmult, rotate, conve]
  aggregation: concat
  evaluator: kge_adapter
  normalize_p: 0.0

import: [semantic_matching_energy]
kge_adapter:
  model:
    type: semantic_matching_energy