import: [literale_distmult,reciprocal_relations_model]

job.type: search
search.type: grid

model: literale_distmult

dataset:
  name: fb15k-237
  files:
    train:
      source: train_base
    valid:
      source: valid_base

train:
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    threshold: 0.0001
  batch_size: 256
  type: negative_sampling

lookup_embedder:
  dim: 256

reciprocal_relations_model:
  base_model:
    type: literale_distmult

grid_search.parameters:
  train.loss: [kl,margin_ranking,bce]
  train.optimizer.default.args.lr: [0.01,0.1,0.5,1.0]
  lookup_embedder.regularize_args.p: [1,2]