1vsAll:
  class_name: TrainingJob1vsAll
KvsAll:
  class_name: TrainingJobKvsAll
  label_smoothing: 0.0
  query_types:
    _po: true
    s_o: false
    sp_: true
ax_search:
  class_name: AxSearchJob
  num_sobol_trials: -1
  num_trials: 10
  parameter_constraints: []
  parameters: []
  sobol_seed: 0
console:
  format: {}
  quiet: false
conve:
  2D_aspect_ratio: 2
  class_name: ConvE
  convolution_bias: true
  entity_embedder:
    +++: +++
    dropout: -0.4457199978380867
    regularize_weight: 8.605027799155396e-15
    type: lookup_embedder
  feature_map_dropout: 0.48769345636955713
  filter_size: 3
  padding: 0
  projection_dropout: 0.5
  relation_embedder:
    +++: +++
    dropout: 0.11757230155305998
    regularize_weight: 2.231687936571624e-14
    type: lookup_embedder
  round_dim: true
  stride: 1
dataset:
  +++: +++
  files:
    +++: +++
    entity_ids:
      filename: entity_ids.del
      type: map
    entity_strings:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_ids.del
      type: map
    relation_strings:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      size: 152
      split_type: test
      type: triples
    test_without_unseen:
      filename: test_without_unseen.del
      size: 152
      split_type: test
      type: triples
    train:
      filename: train.del
      size: 4565
      split_type: train
      type: triples
    train_sample:
      filename: train_sample.del
      size: 109
      split_type: train
      type: triples
    valid:
      filename: valid.del
      size: 109
      split_type: valid
      type: triples
    valid_without_unseen:
      filename: valid_without_unseen.del
      size: 109
      split_type: valid
      type: triples
  name: toy
  num_entities: 280
  num_relations: 112
  pickle: true
entity_ranking:
  chunk_size: -1
  class_name: EntityRankingJob
  filter_splits:
  - train
  - valid
  filter_with_test: true
  hits_at_k_s:
  - 1
  - 3
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  metrics_per:
    argument_frequency: false
    head_and_tail: false
    relation_type: true
  tie_handling:
    atol: 1e-05
    rtol: 1e-04
    type: rounded_mean_rank
    warn_only: true
eval:
  batch_size: 256
  num_workers: 0
  pin_memory: false
  split: valid
  trace_level: example
  type: entity_ranking
grid_search:
  class_name: GridSearchJob
  parameters:
    +++: +++
  run: true
import:
- reciprocal_relations_model
- conve
job:
  device: cpu
  type: train
lookup_embedder:
  class_name: LookupEmbedder
  dim: 242
  dropout: 0.0
  initialize: xavier_normal_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 2.568825067721716e-05
    uniform_:
      a: -0.43447215763614
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  normalize:
    p: -1.0
  pretrain:
    ensure_all: false
    model_filename: ''
  regularize: lp
  regularize_args:
    +++: +++
    p: 3
    weighted: true
  regularize_weight: 0.0
  round_dim_to: []
  sparse: false
manual_search:
  class_name: ManualSearchJob
  configurations: []
  run: true
model: reciprocal_relations_model
modules:
- kge.job
- kge.model
- kge.model.embedder
- kge.model.ensemble
negative_sampling:
  class_name: TrainingJobNegativeSampling
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''
  frequency:
    smoothing: 1
  implementation: batch
  num_samples:
    o: -1
    p: -1
    s: 3
  sampling_type: uniform
  shared: false
  shared_type: default
  with_replacement: true
random_seed:
  default: -1
  numba: -1
  numpy: -1
  python: -1
  torch: -1
reciprocal_relations_model:
  base_model:
    +++: +++
    entity_embedder:
      dim: 242
    relation_embedder:
      dim: 242
    type: conve
  class_name: ReciprocalRelationsModel
search:
  device_pool: []
  num_workers: 1
  on_error: abort
  type: ax_search
train:
  abort_on_nan: true
  auto_correct: true
  batch_size: 256
  checkpoint:
    every: 5
    keep: 3
    keep_init: true
  loss: kl
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    factor: 0.95
    mode: max
    patience: 9
    threshold: 0.0001
  lr_warmup: 0
  max_epochs: 400
  num_workers: 0
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.004276645525573683
      type: Adagrad
  pin_memory: false
  split: train
  subbatch_auto_tune: false
  subbatch_size: -1
  trace_level: epoch
  type: 1vsAll
  visualize_graph: false
training_loss:
  class_name: TrainingLossEvaluationJob
user:
  +++: +++
valid:
  early_stopping:
    patience: 10
    threshold:
      epochs: 50
      metric_value: 0.05
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: float("nan")
  metric_max: true
  split: valid
  trace_level: epoch
