1vsAll:
  class_name: TrainingJob1vsAll
KvsAll:
  class_name: TrainingJobKvsAll
  label_smoothing: 0.0
  query_types:
    _po: true
    s_o: false
    sp_: true
ax_search:
  class_name: AxSearchJob
  num_sobol_trials: -1
  num_trials: 10
  parameter_constraints: []
  parameters: []
  sobol_seed: 0
console:
  format: {}
  quiet: false
conve:
  2D_aspect_ratio: 2
  class_name: ConvE
  convolution_bias: true
  entity_embedder:
    +++: +++
    dropout: 0.2
    type: lookup_embedder
  feature_map_dropout: 0.2
  filter_size: 3
  padding: 0
  projection_dropout: 0.3
  relation_embedder:
    +++: +++
    dropout: 0.2
    type: lookup_embedder
  round_dim: false
  stride: 1
dataset:
  +++: +++
  files:
    +++: +++
    entity_ids:
      filename: entity_ids.del
      type: map
    entity_strings:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_ids.del
      type: map
    relation_strings:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      type: triples
    train:
      filename: train.del
      type: triples
    valid:
      filename: valid.del
      type: triples
  name: toy
  num_entities: -1
  num_relations: -1
  pickle: true
entity_ranking:
  chunk_size: 5000
  class_name: EntityRankingJob
  filter_splits:
  - train
  - valid
  filter_with_test: true
  hits_at_k_s:
  - 1
  - 3
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  metrics_per:
    argument_frequency: false
    head_and_tail: false
    relation_type: true
  tie_handling:
    atol: 1e-05
    rtol: 1e-04
    type: rounded_mean_rank
    warn_only: true
eval:
  batch_size: 256
  num_workers: 0
  pin_memory: false
  split: valid
  trace_level: epoch
  type: entity_ranking
grid_search:
  class_name: GridSearchJob
  parameters:
    +++: +++
  run: true
import:
- reciprocal_relations_model
- rotate
job:
  device: cpu
  type: train
lookup_embedder:
  class_name: LookupEmbedder
  dim: 242
  dropout: 0.0
  initialize: xavier_normal_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 2.0846745139962994e-05
    uniform_:
      a: -0.838215168722691
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  normalize:
    p: -1.0
  pretrain:
    ensure_all: false
    model_filename: ''
  regularize: lp
  regularize_args:
    +++: +++
    p: 2
    weighted: false
  regularize_weight: 0.0
  round_dim_to: []
  sparse: false
manual_search:
  class_name: ManualSearchJob
  configurations: []
  run: true
model: reciprocal_relations_model
modules:
- kge.job
- kge.model
- kge.model.embedder
- kge.model.ensemble
negative_sampling:
  class_name: TrainingJobNegativeSampling
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''
  frequency:
    smoothing: 1
  implementation: triple
  num_samples:
    o: 292
    p: 0
    s: 25
  sampling_type: uniform
  shared: false
  shared_type: default
  with_replacement: true
random_seed:
  default: -1
  numba: -1
  numpy: -1
  python: -1
  torch: -1
reciprocal_relations_model:
  base_model:
    +++: +++
    relation_embedder:
      dim: 121
    type: rotate
  class_name: ReciprocalRelationsModel
rotate:
  class_name: RotatE
  entity_embedder:
    +++: +++
    dropout: -0.20997447613626719
    regularize_weight: 1.0112561331264489e-06
    type: lookup_embedder
  l_norm: 2.0
  normalize_phases: true
  relation_embedder:
    +++: +++
    dim: -1
    dropout: -0.17978530656546354
    initialize: uniform_
    initialize_args:
      uniform_:
        a: -3.14159265359
        b: 3.14159265359
    regularize_weight: 9.896801914862831e-18
    type: lookup_embedder
search:
  device_pool: []
  num_workers: 1
  on_error: abort
  type: ax_search
train:
  abort_on_nan: true
  auto_correct: true
  batch_size: 128
  checkpoint:
    every: 5
    keep: 3
    keep_init: true
  loss: bce
  loss_arg: 10.552413063123822
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    factor: 0.95
    mode: max
    patience: 6
    threshold: 0.0001
  lr_warmup: 0
  max_epochs: 400
  num_workers: 0
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.22032075441824278
      type: Adagrad
  pin_memory: false
  split: train
  subbatch_auto_tune: true
  subbatch_size: -1
  trace_level: epoch
  type: negative_sampling
  visualize_graph: false
training_loss:
  class_name: TrainingLossEvaluationJob
user:
  +++: +++
valid:
  early_stopping:
    patience: 10
    threshold:
      epochs: 50
      metric_value: 0.05
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: float("nan")
  metric_max: true
  split: valid
  trace_level: epoch
