job.type: search

import: [reciprocal_relations_model, multilayer_perceptron]

dataset:
  name: fb15k-237
  files:
    train:
      source: train_base
    valid:
      source: valid_base

model: reciprocal_relations_model

reciprocal_relations_model:
  base_model:
    type: multilayer_perceptron

lookup_embedder:
  dim: 256
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.1

train:
  batch_size: 256
  loss: kl
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 400
  optimizer:
    default:
      type: Adagrad
  type: negative_sampling

valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example

search.type: grid
grid_search.parameters:
  multilayer_perceptron.dropout: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  train.optimizer.default.args.lr: [0.1, 0.01. 0.001, 0.0001, 0.00001]
  lookup_embedder.normalize.p: [-1., 2.]






