job.type: train

import: [reciprocal_relations_model, semantic_matching_energy]

dataset:
  name: fb15k-237
  files:
    train:
      source: train_base
    valid:
      source: valid_base

model: reciprocal_relations_model

reciprocal_relations_model:
  base_model:
    type: semantic_matching_energy

semantic_matching_energy:
  #dropout: 0.0

lookup_embedder:
  dim: 256
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.1
  normalize:
    p: -1

train:
  batch_size: 256
  loss: kl
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 400
  optimizer:
    default:
      type: Adagrad
    args:
      lr: 0.1
  type: negative_sampling

valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example