import: [lookup_embedder]

pca:
  entity_reduction: 0.8
  relation_reduction: 0.8

autoencoder_reduction:
  epochs: 50
  lr: 1e-1
  weight_decay: 1e-8
  entity_reduction: 0.5
  relation_reduction: 0.5

autoencoder:
  num_layers: 3
  dropout: 0.2

oneton:
  entity_reduction: 0.75
  relation_reduction: 0.75
  epochs: 50
  entity_embedder:
    type: lookup_embedder
    +++: +++
  relation_embedder:
    type: lookup_embedder
    +++: +++