import: [lookup_embedder]

pca:
  entity_reduction: 0.5
  relation_reduction: 0.5

autoencoder_reduction:
  epochs: 10
  lr: 1e-1
  batch_size: 64
  weight_decay: 1e-8
  entity_reduction: 0.5
  relation_reduction: 0.5

autoencoder:
  num_layers: 1
  dropout: 0.2

oneton:
  entity_reduction: 0.5
  relation_reduction: 0.5
  epochs: 10
  entity_embedder:
    type: lookup_embedder
    +++: +++
  relation_embedder:
    type: lookup_embedder
    +++: +++