job.type: search
dataset:
  name: wnrr
  files:
    train:
      source: train_ensemble
    valid:
      source: valid_ensemble

train:
  type: negative_sampling
  batch_size: 256
  loss: kl
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 400
  optimizer.default:
    type: Adagrad

negative_sampling:
  num_samples:
    s: 30

eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example

valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

model: embedding_ensemble

embedding_ensemble:
  base_models: [complex, literale_distmult, rotate, conve]
  aggregation: autoencoder
  evaluator: finetuning

autoencoder_reduction:
  epochs: 400
  lr: 0.01
  batch_size: 64
  patience: 5
  entity_reduction: 0.2
  relation_reduction: 0.2

autoencoder:
  num_layers: 1
  dropout: 0.5

import: [complex]
kge_adapter:
  model:
    type: complex

finetuning:
  num_layers: 1
  dropout: 0.4 #hp

search.type: grid
grid_search.parameters:
  finetuning.dropout: [ 0.0, 0.1, 0.2, 0.3, 0.4, 0.5 ]
  train.optimizer.default.args.lr: [0.1, 0.01, 0.001, 0.0001, 0.00001]
  embedding_ensemble.normalize_p: [0., 2.]